name: ws-api
recipe: laravel
services:
  appserver:
    type: php
    webroot: public
  database:
    type: mysql
    creds:
      user: ws-api
      password: laravel12345
      database: database
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    build:
      - npm install
# events:
#   post-start:
#     - php artisan migrate:refresh --seed
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  npx:
    service: node
  gulp:
    service: node